In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as snb

In [2]:
df = pd.read_csv('Hiring.csv')

In [3]:
df

expirence  test_score  interview_score  Salary
0       NaN         8.0                9   50000
1       NaN         8.0                6   45000
2      five         6.0                7   60000
3       two        10.0               10   65000
4     seven         9.0                6   68000
5     three         7.0               10   62000
6       ten         NaN                7   72000
7    eleven         7.0                8   80000

In [4]:
from word2number import w2n

In [5]:
df.expirence = df.expirence.fillna('zero')

In [6]:
df

expirence  test_score  interview_score  Salary
0      zero         8.0                9   50000
1      zero         8.0                6   45000
2      five         6.0                7   60000
3       two        10.0               10   65000
4     seven         9.0                6   68000
5     three         7.0               10   62000
6       ten         NaN                7   72000
7    eleven         7.0                8   80000

In [7]:
#Convert Word to number
df.expirence = df.expirence.apply(w2n.word_to_num)

In [8]:
df

expirence  test_score  interview_score  Salary
0          0         8.0                9   50000
1          0         8.0                6   45000
2          5         6.0                7   60000
3          2        10.0               10   65000
4          7         9.0                6   68000
5          3         7.0               10   62000
6         10         NaN                7   72000
7         11         7.0                8   80000

In [9]:
df.isnull().sum()

expirence          0
test_score         1
interview_score    0
Salary             0
dtype: int64

In [10]:
df['test_score'] = df['test_score'].replace(np.NaN,df['test_score'].mean())

In [11]:
df.isnull().sum()

expirence          0
test_score         0
interview_score    0
Salary             0
dtype: int64

In [12]:
df

expirence  test_score  interview_score  Salary
0          0    8.000000                9   50000
1          0    8.000000                6   45000
2          5    6.000000                7   60000
3          2   10.000000               10   65000
4          7    9.000000                6   68000
5          3    7.000000               10   62000
6         10    7.857143                7   72000
7         11    7.000000                8   80000

In [13]:
from sklearn import linear_model

In [14]:
reg = linear_model.LinearRegression()

In [15]:
reg.fit(df[['expirence','test_score','interview_score']],df.Salary)

LinearRegression()

In [16]:
#First Prediction
reg.predict([[2,9,6]])

array([52433.0430926])

In [17]:
#Calculation Process
reg.coef_

array([2795.72726642, 1638.44407823, 2400.64770278])

In [18]:
reg.intercept_

17691.70563897096

In [19]:
#Calculation
2795.72726642*2+1638.44407823*9+2400.64770278*6+17691.70563897096

52433.04309256096

In [20]:
#Second Prediction
reg.predict([[12,10,10]])

array([91631.35064618])

In [21]:
2795.72726642*12+1638.44407823*10+2400.64770278*6+17691.70563897096

82028.75983499097

In [26]:
#Now Checking the Predction of our Next CSV file
df1 = pd.read_csv('Next.csv')

In [27]:
df1

expirence  test_score  interview_score
0          8          10               10
1          5           7                5
2          9           8                7
3         12           9                8
4         15          10               10
5          7           6                7
6         13           7               10
7          9           8                8
8         18          10               10
9          1           3                5

In [29]:
p = reg.predict(df1)

In [30]:
p

array([ 80448.4415805 ,  55142.68903262,  72765.3375821 ,  85191.61116238,
       100018.53244545,  63896.9948928 ,  89511.74567791,  75165.98528489,
       108405.71424471,  37406.00365401])

In [31]:
df1['Salary'] = p

In [32]:
df1

expirence  test_score  interview_score         Salary
0          8          10               10   80448.441580
1          5           7                5   55142.689033
2          9           8                7   72765.337582
3         12           9                8   85191.611162
4         15          10               10  100018.532445
5          7           6                7   63896.994893
6         13           7               10   89511.745678
7          9           8                8   75165.985285
8         18          10               10  108405.714245
9          1           3                5   37406.003654

In [33]:
df1.to_csv('Salary Range.csv')