In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as snb

In [2]:
#Load Datasheet
df = pd.read_csv('HomePrice.csv')

In [3]:
df

Area  Bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [4]:
df.isnull().sum()

Area        0
Bedrooms    1
age         0
price       0
dtype: int64

In [9]:
df['Bedrooms'] = df['Bedrooms'].replace(np.NaN,df['Bedrooms'].mean())

In [10]:
df.isnull().sum()

Area        0
Bedrooms    0
age         0
price       0
dtype: int64

In [11]:
df

Area  Bedrooms  age   price
0  2600      3.00   20  550000
1  3000      4.00   15  565000
2  3200      3.75   18  610000
3  3600      3.00   30  595000
4  4000      5.00    8  760000

In [12]:
#Fitting Model
from sklearn import linear_model

In [13]:
reg = linear_model.LinearRegression()

In [14]:
reg.fit(df[['Area','Bedrooms','age']],df.price)

LinearRegression()

In [15]:
reg.coef_

array([    230.59826103, -167936.0972381 ,  -18554.36548529])

In [16]:
reg.intercept_

827087.5203080806

In [18]:
#For First Test Data
reg.predict([[3000,3,40]])

array([272899.39226187])

In [21]:
#Calculation Process
230.59826103*3000+(-167936.0972381*3)+(-18554.36548529*40)+827087.5203080806

272899.39227218064

In [19]:
#For Second Test Data
reg.predict([[2500,4,5]])

array([639066.95649558])

In [22]:
#Calculation Process
230.59826103*2500+(-167936.0972381*4)+(-18554.36548529*5)+827087.5203080806

639066.9565042306